<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>promise</title>
</head>
<body>
    <script>
        // resolve.reject,all,ract

        // let promise =new Promise((resolve,reject)=>{
        //     // resolve(11111);
        //     reject(222);
        // })

        // promise.then(res=>{
        //     console.log("成功");
        //     console.log(res); 

        // }).catch(error=>{
        //     console.log("失败");
        //     console.log(error); 
        // })

        //链式

        function promise1(status){
            return new Promise((resolve,reject)=>{
                if(status){
                    console.log("第一个promise成功");
                    resolve("第一个promise返回数据成功")
                }else{
                    console.log("第一个promise失败");
                    reject("第一个promise返回数据失败");
                }
            })
        }

        function promise2(status){
            return new Promise((resolve,reject)=>{
                if(status){
                    console.log("第二个promise成功");
                    resolve("第二个promise返回数据成功")
                }else{
                    console.log("第二个promise失败");
                    reject("第二个promise返回数据失败");
                }
            })
        }

        function promise3(status){
            return new Promise((resolve,reject)=>{
                if(status){
                    console.log("第三个promise成功");
                    resolve("第三个promise返回数据成功")
                }else{
                    console.log("第三个promise失败");
                    reject("第三个promise返回数据失败");
                }
            })
        }

        // promise1(true).then(response=>{
        //     console.log(response);
        //     return promise2(true)
        // }).then(res=>{
        //     console.log(res);
        //     return promise3(false)
        // }).then(res=>{
        //     console.log(res);
        // }).catch(error=>{
        //     console.log(error)
        // })


        // 全部执行成功，才会执行then回调，但是数组里面的函数都会调用
        // Promise.all([promise1(false),promise2(false)]).then(res=>{
        //     console.log(res);
        // }).catch(error=>{
        //     console.log(error);
        // })
        
        // 无论执行成功或者失败,都会继续往下执行
        // 里面有一个执行成功，就算成功，
        // 但是第一个返回失败，就返回失败
        Promise.race([promise1(true),promise2(false),promise3(false)]).then(res=>{
            console.log("执行成功");
            console.log(res);
        }).catch(error=>{
            console.log("执行失败");
            console.log(error);
        })

    </script>
</body>
</html>